// Auto-generated by scripts/convert_cjk_font_to_epdfontdata.py
// Source: /tmp/crosspoint-jp/lib/GfxRenderer/cjk_ui_font_20.h
// sha256:f6c5030ee67696322c6c25551198e5af02f096dc3d97bcf7e1e877b0de2ac57b
// Do not edit manually — re-run the converter to regenerate.
#pragma once
#include "EpdFontData.h"

// 20px CJK UI font: 3420 glyphs, advanceY=24, ascender=16, descender=4
extern const EpdFontData cjk_ui_20_font_data;
static constexpr uint16_t CJK_UI_20_GLYPH_COUNT = 3420;
